# cf-fusion wrangler 配置
name = "cf-fusion"
main = "_worker.js"
compatibility_date = "2025-01-01"
workers_dev = true

# 绑定 KV 命名空间(用于图形化配置 / 优选 IP / 连接日志)
[[kv_namespaces]]
binding = "KV"
id = "52626c478acf403d9f50187aabb36472"

[vars]
# 后台密码
ADMIN_PASS = "joyboy"
# 自定义订阅路径
CUSTOM_PATH = "shan"
# 全局反代 IP / 域名
PROXYIP = "ProxyIP.US.CMLiussss.net"

# 定时触发器 (每 7 小时自动拉取并更新优选 IP)
[triggers]
crons = ["0 */7 * * *"]
